version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.0
    steps:
      - checkout
      - run: sudo npm install --global yarn
      - run: yarn global add bs-platform
      - run: yarn
      - run: yarn test