version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.0
    steps:
      - checkout
      - run: sudo chown -R $(whoami) /usr/local/lib/node_modules
      - run: yarn global add bs-platform
      - run: yarn
      - run: yarn test